# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDd6sPC9VWZHPaANwyLSixTt_EMtpSF5
"""

# Definición de Workloads
C1 = [
    ("P01", "Health Check Service",        1,  6),
    ("P02", "Cache Refresh",               2, 11),
    ("P03", "Log Processing",              3, 16),
    ("P04", "Thumbnail Generation",        4, 21),
    ("P05", "Search Index Update",         5, 26),
    ("P06", "Analytics Batch",             6, 31),
    ("P07", "Recommendation Refresh",      7, 36),
    ("P08", "Video Processing",            8, 40),
    ("P09", "Database Maintenance",        9, 45),
    ("P10", "Machine Learning Inference", 10, 50)
]

C2 = [
    ("Q10", "Realtime Analytics",       10,  60),
    ("Q20", "Search Reindexing",        20, 100),
    ("Q30", "Video Transcoding",        30, 120),
    ("Q35", "Database Replication",     35, 130),
    ("Q40", "Model Inference Batch",    40, 135),
    ("Q45", "Large ETL Pipeline",       45, 140),
    ("Q50", "Database Migration",       50, 150)
]

# Capacidades requeridas por la tarea
capacities = [0, 5, 20, 35, 50, 65, 80, 95, 110, 140]

# 1. Algoritmo Greedy (necesario para el récord inicial de B&B)
def solve_greedy(jobs, capacity_W):
    if capacity_W <= 0:
        return 0, []

    # Ordenar por densidad (vi/wi) descendente, luego menor costo, luego id
    sorted_jobs = sorted(
        jobs,
        key=lambda j: (- (j[3] / j[2]), j[2], j[0])
    )

    total_relief = 0
    current_cost = 0
    chosen_ids = []

    for j_id, name, cost, relief in sorted_jobs:
        if current_cost + cost <= capacity_W:
            current_cost += cost
            total_relief += relief
            chosen_ids.append(j_id)

    return total_relief, chosen_ids

# Algoritmo Exact Branch and Bound
def solve_branch_and_bound(jobs, capacity_W):
    if capacity_W <= 0:
        return 0, []

    # Ordenar por densidad vi/wi para que el Upper Bound sea eficiente
    sorted_jobs = sorted(
        jobs,
        key=lambda j: (- (j[3] / j[2]), j[2], j[0])
    )

    n = len(sorted_jobs)
    best_value = 0
    best_selection = []

    # Inicializar récord (incumbent) usando Greedy
    g_val, g_sel = solve_greedy(jobs, capacity_W)
    best_value = g_val
    best_selection = g_sel

    # Función para calcular el límite superior
    def compute_upper_bound(index, current_cost, current_relief):
        bound = current_relief
        rem_cap = capacity_W - current_cost
        for i in range(index, n):
            j_id, name, cost, relief = sorted_jobs[i]
            if rem_cap >= cost:
                rem_cap -= cost
                bound += relief
            else:
                bound += (rem_cap / cost) * relief
                break
        return bound

    # Función recursiva de búsqueda con poda
    def backtrack(index, current_cost, current_relief, current_ids):
        nonlocal best_value, best_selection

        if current_relief > best_value:
            best_value = current_relief
            best_selection = list(current_ids)

        if index == n:
            return

        # Poda: Si el límite superior no supera nuestro récord, adiós a esta rama
        ub = compute_upper_bound(index, current_cost, current_relief)
        if ub <= best_value:
            return

        # Rama 1: Incluir el trabajo (si cabe)
        j_id, name, cost, relief = sorted_jobs[index]
        if current_cost + cost <= capacity_W:
            current_ids.append(j_id)
            backtrack(index + 1, current_cost + cost, current_relief + relief, current_ids)
            current_ids.pop()

        # Rama 2: Excluir el trabajo
        if compute_upper_bound(index + 1, current_cost, current_relief) > best_value:
            backtrack(index + 1, current_cost, current_relief, current_ids)

    backtrack(0, 0, 0, [])
    return best_value, best_selection

# Prueba rápida con el workload C1 y capacidad W = 50
relief, ids = solve_branch_and_bound(C1, 50)
print("Mejor relieve:", relief)
print("Trabajos elegidos:", ids)

import time
import os
import matplotlib.pyplot as plt
import numpy as np

# 1. Definición del Método Greedy
def solve_greedy(jobs, capacity_W):
    if capacity_W <= 0:
        return 0, []
    sorted_jobs = sorted(jobs, key=lambda j: (- (j[3] / j[2]), j[2], j[0]))
    total_relief = 0
    current_cost = 0
    chosen_ids = []
    for j_id, name, cost, relief in sorted_jobs:
        if current_cost + cost <= capacity_W:
            current_cost += cost
            total_relief += relief
            chosen_ids.append(j_id)
    return total_relief, chosen_ids

# 2. Definición de Programación Dinámica (DP)
def solve_dp(jobs, capacity_W):
    if capacity_W <= 0:
        return 0, []
    dp = [0] * (capacity_W + 1)
    tracking = [[] for _ in range(capacity_W + 1)]
    for j_id, name, cost, relief in jobs:
        for c in range(capacity_W, cost - 1, -1):
            if dp[c - cost] + relief > dp[c]:
                dp[c] = dp[c - cost] + relief
                tracking[c] = tracking[c - cost] + [j_id]
    max_relief = dp[capacity_W]
    best_c = capacity_W
    for c in range(capacity_W + 1):
        if dp[c] > max_relief:
            max_relief = dp[c]
            best_c = c
    return max_relief, tracking[best_c]

# (Tu Branch-and-Bound ya lo tienes arriba, asegurate de tenerlo cargado como solve_branch_and_bound)

# Interfaz unificada requerida por la tarea
def solve_method(jobs, capacity_W, method_name):
    if method_name == "Greedy":
        return solve_greedy(jobs, capacity_W)
    elif method_name == "Dynamic Programming":
        return solve_dp(jobs, capacity_W)
    elif method_name == "Branch-and-Bound":
        return solve_branch_and_bound(jobs, capacity_W)
    else:
        raise ValueError("Método desconocido")

# 3. Protocolo de Benchmarking y Experimentos
capacities = [20, 35, 50, 65, 80, 95, 110, 140]
edge_capacities = [0, 5]
all_caps = edge_capacities + capacities

workloads = {"C1": C1, "C2": C2}
methods = ["Greedy", "Dynamic Programming", "Branch-and-Bound"]

results = []

print("--- INICIANDO BENCHMARK GENERAL Y VALIDACIONES CRUZADAS ---")
for w_name, w_data in workloads.items():
    for cap in all_caps:
        if w_name == "C1" and cap == 5:
            continue # El edge check W=5 es específico para C2 según instrucciones

        opt_val_dp = None
        opt_val_bb = None

        for m_name in methods:
            # Medir al menos 5 repeticiones para la mediana
            times = []
            val, sel = 0, []
            for _ in range(5):
                t0 = time.perf_counter()
                val, sel = solve_method(w_data, cap, m_name)
                t1 = time.perf_counter()
                times.append((t1 - t0) * 1000.0)

            median_time = np.median(times)

            # Validaciones automáticas obligatorias
            job_dict = {j[0]: (j[2], j[3]) for j in w_data}
            if cap > 0 and val > 0:
                for j_id in sel:
                    assert j_id in job_dict
                assert len(sel) == len(set(sel))
                assert sum(job_dict[j][0] for j in sel) <= cap
                assert sum(job_dict[j][1] for j in sel) == val

            if m_name == "Dynamic Programming":
                opt_val_dp = val
            elif m_name == "Branch-and-Bound":
                opt_val_bb = val

            results.append({
                "workload": w_name,
                "capacity": cap,
                "method": m_name,
                "median_time_ms": median_time,
                "returned_value": val,
                "chosen_ids": sel
            })

        # Verificar que DP y B&B den exactamente el mismo resultado óptimo
        if opt_val_dp is not None and opt_val_bb is not None:
            assert opt_val_dp == opt_val_bb, f"Discrepancia óptima en {w_name} con W={cap}: DP={opt_val_dp}, B&B={opt_val_bb}"

print("¡Todos los experimentos y validaciones cruzadas pasaron con éxito!")

# 4. Generación y visualización directa en el Colab
os.makedirs("figures", exist_ok=True)

for w_name in ["C1", "C2"]:
    w_res = [r for r in results if r["workload"] == w_name and r["capacity"] > 5]
    caps_plot = capacities

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Runtime vs Capacity (Log Scale)
    for m_name in methods:
        runtimes = [next(r["median_time_ms"] for r in w_res if r["capacity"] == c and r["method"] == m_name) for c in caps_plot]
        ax1.plot(caps_plot, runtimes, marker='o', label=m_name)
    ax1.set_title(f"Runtime vs Capacity ({w_name})")
    ax1.set_xlabel("Offloading Capacity W")
    ax1.set_ylabel("Median Runtime (ms) [Log Scale]")
    ax1.set_yscale('log')
    ax1.grid(True, which="both", ls="--")
    ax1.legend()

    # Greedy Value Gap vs Capacity
    opt_vals = [next(r["returned_value"] for r in w_res if r["capacity"] == c and r["method"] == "Dynamic Programming") for c in caps_plot]
    greedy_vals = [next(r["returned_value"] for r in w_res if r["capacity"] == c and r["method"] == "Greedy") for c in caps_plot]
    gaps = [o - g for o, g in zip(opt_vals, greedy_vals)]

    ax2.plot(caps_plot, gaps, marker='s', color='crimson', label="Gap (V_optimal - V_greedy)")
    ax2.set_title(f"Greedy Value Gap vs Capacity ({w_name})")
    ax2.set_xlabel("Offloading Capacity W")
    ax2.set_ylabel("Load Relief Gap")
    ax2.grid(True, which="both", ls="--")
    ax2.legend()

    plt.tight_layout()

    # 1. Guardar archivos en la carpeta figures (para los deliverables)
    plt.savefig(f"figures/metrics_{w_name}.png", dpi=300)
    plt.savefig(f"figures/metrics_{w_name}.pdf", format="pdf")

    # 2. MOSTRAR DIRECTAMENTE EN EL COLAB de forma ordenada
    plt.show()